name: next_ddl
description: "Next DDL deadline app."
publish_to: 'none'
version: 1.1.9+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^19.4.2
  flutter_riverpod: ^2.6.1
  flutter_timezone: ^4.1.1
  file_picker: ^10.3.2
  package_info_plus: ^8.3.1
  path: ^1.9.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  timezone: ^0.10.1
  http: ^1.3.0
  open_filex: ^4.7.0
  url_launcher: ^6.3.1
  window_manager: ^0.5.1
  flex_color_picker: ^3.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
